### PR TITLE
dev -> master March 20, 2024

### PR DESCRIPTION
**Pull request by greensomes**
[:sunglasses: dev](https://dev-nrrd.app.cloud.gov)

Changes proposed in this pull request:

- [x] Explore data map button resize - @eelzi-ONRR 
- [x] Fixes hover area on either side of explore data map button - @eelzi-ONRR 
- [x] Fixes rounding issue in currency formatting function  - @cthomasONRR
- [x] Removes ">" from disbursement sources card - @eelzi-ONRR 
- [x] Fixes accessibility issues on federal sales data download page - @eelzi-ONRR 
- [x] Revenue True-Up  - @cthomasONRR
- [x] Feb 24 Revenue   - @cthomasONRR
- [x] Nov 23 Production   - @cthomasONRR
- [x] Nov 23 OGOR-B -  - @cthomasONRR
- [x] FY 23 Production  - @cthomasONRR
- [x] Updated accessibility statement page  - @cthomasONRR
- [x] Feb 24 Disbursements - @lpgoldstein 

**SALES DATA DOWNLOAD PAGE:**
- [x] Add external link indicators to download page and diagram - @cthomasONRR
- [x] Clarify the meaning of "ONRR aggregates data" - @AlexandracmONRR 
- [x] Provide definition and hover over for quality and gravity bank - @AlexandracmONRR 
- [x] Update Data Download page text to have plain language: 
   - [x] Scope - @AlexandracmONRR 
   - [x] COIVD relief - @AlexandracmONRR 
   - [x] Sales & accounting year - @AlexandracmONRR 
   - [x] Data Dictionary: Calendar Year, Land Category (onshore and offshore), Sales Volume - @cthomasONRR 
   - [x] Glossary: Not tied to a commodity, Processing Allowances, Sales Year  - @cthomasONRR

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Production Fiscal Year**
	
- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card 
- Select a year and select a state with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected
 
- Select a year and select a county with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- Select a year and select an offshore area, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.
- [ ] Add Nationwide Federal Card and verify the expected information is displayed.
- [ ] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Production Summary and Top Nationwide Locations
- Verify breakdowns by production type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data, in the 'Period' category, filter to either 'Calendar Year' or 'Fiscal Year' and check the following:
- [ ] One Land Type filter
- [ ] One State
- [ ] One Offshore Region
- [ ] One to three Product
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State 
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Revenue True-Up checklist:**

- [x] In 2015, the bonus revenue is decreasing by $27,202.03 due to a state coal lease bonus payment being reversed
- [x] In 2016, the other revenue is decreasing by $4,508.19 due to a code change to our total revenue query
- [x] In 2017, the other revenue is increasing by $4,508.19 due to a code change to our total revenue query
- [x] In 2019-2023 the rent revenue is increasing each year by $1,853.50 due to a state oil shale lease that has 50% federal interest and has a legit rent obligation

**Comment by eelzi-ONRR** [comment]
All the previously identified accessibility problems are resolved but the new product codes table is causing a violation because it needs a table name.

What issue is "Fixes rounding issue in currency formatting function" referring to? We fixed #3111 in the last merge and I can't find an issue that seems to match this described problem for this merge.

**Comment by lpgoldstein** [comment]
- [x] Make sure the downloaded data matches the raw data. Raw data
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Jeff's "Fixes rounding issue in currency formatting function" refers to the homepage revenue and disbursement tables. At one point during the data PR, instead of the normal number format "$#,###,###.##" the table said "$##million". This was because a explore data card fix accidentally was also applied to the homepage. Jeff fixed this and made sure it wouldn't happen again. I don't believe there was a specific PR for it.

**Review by eelzi-ONRR — APPROVED** [review]
Jeff added the product code table name so now everything I reviewed looks good!

**Review by lpgoldstein — APPROVED** [review]

**Review by cthomasONRR — APPROVED** [review]
Everything I checked looks good! Thanks @greensomes for all your help!

**Pull request merged**
