### PR TITLE
SVG Alt Text - Accessibility Violation Fix 

### PR DESCRIPTION
**Pull request by Maroyafaied**
Fixes #<2524>

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2524-alt-text-for-svg-elements/)

Changes proposed in this pull request:

-
-
-

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@greensomes @eelzi-ONRR I added the alt text for the ONRR logo. I'll mark it off in the issue #2524 
image

**Comment by eelzi-ONRR** [comment]
Reviewed for the ONRR logo - looks good!

**Comment by Maroyafaied** [comment]
@eelzi-ONRR @greensomes I added a title for the question mark icon. I'll check it off the list. 
image

**Comment by Maroyafaied** [comment]
@eelzi-ONRR Here's a checklist to help with review, I'll check off what I reviewed. 

- [ ] colored squares in the bar chart keys that indicate the unique recipients, sources, etc. (found on [fact sheet](https://revenuedata.doi.gov/fact-sheet/), [homepage](https://revenuedata.doi.gov/))

- [ ] disbursements bar chart by recipient ([fact sheet](https://revenuedata.doi.gov/fact-sheet/), [homepage](https://revenuedata.doi.gov/)) 

- [ ] disbursements bar chart by source ([fact sheet](https://revenuedata.doi.gov/fact-sheet/), [homepage](https://revenuedata.doi.gov/)) 

- [ ] production bar chart oil  ([homepage](https://revenuedata.doi.gov/)) 

- [ ] production bar chart gas   ([homepage](https://revenuedata.doi.gov/)) 

- [ ] production bar chart coal  ([homepage](https://revenuedata.doi.gov/)) 

- [ ] file box icon ([audits & assurances](https://revenuedata.doi.gov/how-revenue-works/audits-and-assurances))

- [ ] gas bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/))

- [ ] Coal  bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/))

- [ ] Oil bar chart ([fact sheet](https://revenuedata.doi.gov/fact-sheet/))

- [ ] revenue bar chart  ([fact sheet](https://revenuedata.doi.gov/fact-sheet/)

- [ ] revenue by revenue type [homepage](https://revenuedata.doi.gov/))

- [ ] revenue by revenue commodity [homepage](https://revenuedata.doi.gov/))

- [ ] revenue by revenue Source [homepage](https://revenuedata.doi.gov/))

- [ ] trend lines ([Query Data](https://revenuedata.doi.gov/query-data/?dataType=Disbursements))

- [ ] line arrows that connect ownership, leasing, production, revenue, disbursements boxes ([How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))


- [ ] Map legend in lower left corner of map ([Explore Data](https://revenuedata.doi.gov/explore/?dataType=Revenue&location=NF,NA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))

- [ ] ONRR logo ([About](https://revenuedata.doi.gov/about/), [fact sheet](https://revenuedata.doi.gov/fact-sheet/), [Minerals](https://revenuedata.doi.gov/how-revenue-works/minerals))

- [ ] Progress bar on the compare revenue cards, nationwide revenue summary, etc. ([Explore data](https://revenuedata.doi.gov/explore/?dataType=Revenue&location=NF,NA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))

- [ ] ribbon graphic - major commodities in the U.S. ([How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

- [ ] Tool tip question mark icon (many many pages. Lots can be found on [How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

- [ ] Commodities circle charts for revenue data ([Explore Data](https://revenuedata.doi.gov/explore?dataType=Revenue&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))
- [ ]  Commodities circle charts for disbursements data [Explore Data ](https://revenuedata.doi.gov/explore?dataType=Disbursements&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Fiscal%20Year&year=2022)

- [ ]  Commodities circle charts for production data [Explore Data ](https://revenuedata.doi.gov/explore?dataType=Production&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022)

- [ ] Horizontal chart  federal revenue by company ([Explore Data](https://revenuedata.doi.gov/explore?dataType=Revenue&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))

- [ ] Horizontal chart Nationwide revenue by revenue type and source ([Explore Data](https://revenuedata.doi.gov/explore?dataType=Revenue&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Calendar%20Year&year=2022))

- [ ] Horizontal bar chart Nationwide disbursements by recipient and source: [Explore data](https://revenuedata.doi.gov/explore?dataType=Disbursements&location=NF%2CNA&mapLevel=State&offshoreRegions=false&period=Fiscal%20Year&year=2022)

**Comment by eelzi-ONRR** [comment]
@Maroyafaied The disbursements svg title is visible on the factsheet

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I finished review so far. The last three on the list don't have alt text yet, the progress bar still comes up as missing alt text in the Access Assistant tool, and the map lengend has alt text but I think it should be changed from what it currently is. I'll put a draft of what it could be changed to in the other issue

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I've updated the map legend text and fixed the disbursement chart in the fact sheet

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I figured out how to add the alt text for the horizontal bar charts. I'm updating this branch with dev then I'll merge it to dev and we can review everything in the dev to master PR.

**Pull request merged**
