### PR TITLE
Add Product Codes Table

### LINKED ISSUE #3203: Add product code table to Data Download page
- [x] Request included product codes in dataset from DORC
- [x] Include subheading in About the data section "What are product codes?"
- [x] Write 1-2 sentence descriptive text about product codes.
- [x] Include table of product codes (from DORC)

image

### PR DESCRIPTION
**Pull request by AlexandracmONRR**
[Preview](https://nrrd-preview.app.cloud.gov/sites/federal-sales-data-productcodes/downloads/federal-sales/)

Fixes:

- Updated accessibility statement page
- #3203 
- #3262 - Add external link indicators to download page and diagram
- #3215 - Clarify the meaning of "ONRR aggregates data"
- #3197 - Provide definition and hover over for quality and gravity bank
- #3272 - Update Data Download page text to have plain language:
   - [x] Scope
   - [x] COIVD relief
   - [x] Sales & accounting year
   - [x] Data Dictionary: Calendar Year, Land Category (onshore and offshore), Sales Volume
   - [x] Glossary: Not tied to a commodity, Processing Allowances, Sales Year

### CODE REVIEW

**Comment by AlexandracmONRR** [comment]
@cthomasONRR would you be able to review the product code section of the federal sales data download page?

**Review by cthomasONRR — APPROVED** [review]
@AlexandracmONRR Looks good.

**Review by lpgoldstein — APPROVED** [review]
Looks great! Thanks @AlexandracmONRR and @cthomasONRR

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - i reviewed the external link indicators and they all look good!

**Comment by lpgoldstein** [comment]
https://nrrd-preview.app.cloud.gov/sites/federal-sales-data-productcodes/downloads/federal-sales/

**Comment by lpgoldstein** [comment]
image

**Comment by eelzi-ONRR** [comment]
image

**Comment by eelzi-ONRR** [comment]
Inconsistent use of data set and dataset and **the** dataset versus **this** dataset. 

I also think this as a full sentence is unnecessary: "Below are the transaction codes included in the dataset." Can we have a next level of heading used instead and just call it "Federal Sales Dataset Transaction Codes"

image

**Comment by lpgoldstein** [comment]
@eelzi-ONRR I'll do the same thing for the product code table

**Comment by eelzi-ONRR** [comment]
Same with product codes - instead of the sentence "Below are the product codes..." can that be a next level heading that function as a table title? A visible table title would be ideal but not sure we have that ability

**Comment by eelzi-ONRR** [comment]
I think the word "are" needs to go here. 
image

**Comment by eelzi-ONRR** [comment]
It's against 508 to use the word above unless referencing what's directly above. Can we instead use the anchored link to this section and just call it the name of the section: [What is the difference between sales year and accounting year data?](https://nrrd-preview.app.cloud.gov/sites/federal-sales-data-productcodes/downloads/federal-sales/#What-is-the-difference-between-sales-year-and-accounting-year-data)

Also this note doesn't stick out as one. I suggest removing the word note and making the text of the note italicized. 
image

**Comment by eelzi-ONRR** [comment]
Too many ways of referring to the same thing image

**Comment by eelzi-ONRR** [comment]
Love the bullet format, but suggest dropping the ,and and the period at the end. That's a very formal way of writing for print, not web
image

**Comment by eelzi-ONRR** [comment]
Click is ableist. Replace with "Use the arrows...."
image

**Comment by cthomasONRR** [comment]
@AlexandracmONRR @lpgoldstein @eelzi-ONRR I'm done implementing the remainder of Erin's edits.

**Review by eelzi-ONRR — APPROVED** [review]
The changes look good!

**Comment by lpgoldstein** [comment]
All looks good! Kudos for all of the review and updates.

**Pull request merged**
