### PR TITLE
GlossaryUpdate

### LINKED ISSUE #2977: Add definition to "land type" in query tool
DORC team suggested that we explain that land type is land class and land category combined in the query tool

### PR DESCRIPTION
**Pull request by cthomasONRR**
Fixes #2977 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/GlossaryUpdate/)

Changes proposed in this pull request:

- Land Category: Distinguishes between data collected onshore and offshore within NRRD datasets.
- Land Class: Distinguishes federal lands and waters from Native American lands within NRRD datasets.
- Land Type: Combines land class and land category within NRRD's Query Data tool.
- Offshore: Submerged lands located farther than three miles off a state’s coastline, or three marine leagues into the Gulf of Mexico off Texas and western Florida.
- Onshore: Situated or occurring on land.

### CODE REVIEW

**Comment by cthomasONRR** [comment]
Changing the following definitions:

- Land Category: Distinguishes between data collected onshore and offshore within **ONRR** datasets.
- Land Class: Distinguishes federal lands and waters from Native American lands within **ONRR** datasets.
- Land Type: Combines land class and land category within **this website's** Query Data tool.

**Comment by cthomasONRR** [comment]
@Maroyafaied These definitions are updated and ready for your review. Thanks!

**Comment by Maroyafaied** [comment]
@cthomasONRR this looks good, the only thing I'm not sure is needed or not is the word "the" before "ONRR". 
image

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks, those 2 definitions are updated now.

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@cthomasONRR looks great, if you don't have any other changes for this PR then I will merge it to dev. Thanks

**Comment by cthomasONRR** [comment]
@Maroyafaied Feel free to merge into dev!

**Pull request merged**
