### PR TITLE
Dev-->Master 6/23/2023

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] **Added blog** [about pricing table](https://dev-blog-nrrd.app.cloud.gov/intern-pricing-tables/) @lpgoldstein And @eelzi-ONRR 

- [x] **What's New** @lpgoldstein 

- [x] **Version** @lpgoldstein 

- [x] **Explore Data Bug Fix** Revenue type circle chart table heading updated to revenue type from commodoity

**Revenue by company** @cthomasONRR 
- [x] Added corporate crosswalk tab to [excel sheet](https://dev-nrrd.app.cloud.gov/downloads/federal_revenue_by_company.xlsx)
- [x] Changed "Company Name" to "Corporate Name" in [Fields and Definitions ](https://dev-nrrd.app.cloud.gov/downloads/federal-revenue-by-company/#Data-dictionary)

**Production by disposition Monthly February 2023 and historical files** @cthomasONRR 
- [x] Make sure both csv and xls files download and contain the latest data
- [x] Make sure both csv and xls files downloads open for historical data

**Production Monthly February 2023** @cthomasONRR 
- [x]  Make sure the downloaded data matches the raw data. Raw data saved here

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
- [x]  Period - Most recent 12 months
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x]  One Land Type filter
- [x]  One to three Products
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x]  Check graphs match homepage

**Revenue Monthly May 2023** @cthomasONRR 

- [x] Make sure the downloaded data matches the raw data.

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x]  Period - Fiscal Year
- [x] Period - Calendar Year
- [x]  Breakout - Source
- [x] Breakout - Revenue Type
- [x] Breakout - Commodity

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
- [x]   Period - Most recent 12 months
- [x]   Period - Fiscal Year
- [x]   Period - Calendar Year
- [x]   Breakout - Source
- [x]   Breakout - Revenue Type
- [x]   Breakout Commodity

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Disbursements Monthly May 2023** @lpgoldstein 

- [ ] Make sure RI is added to January 2017 data.
- [x] Make sure the downloaded data matches the raw data. Raw data
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**SVG Alt text**

Fact Sheet & Homepage @eelzi-ONRR 
-  [x] colored squares in the bar chart keys that indicate the unique recipients, sources, etc. 
- [x] disbursements bar chart by recipient
- [x] production bar chart oil  
- [x] production bar chart gas    
- [x] production bar chart coal  
- [x] revenue by source
- [x] revenue by recipient

Homepage @Maroyafaied 
- [x] colored squares in the bar chart keys that indicate the unique recipients, sources, etc. 
- [x] production bar chart oil yearly and monthly
- [x] production bar chart gas   yearly and monthly
- [x] production bar chart coal yearly and monthly
- [x] revenue by revenue type yearly and monthly
- [x] revenue by revenue commodity yearly and monthly
- [x] revenue by revenue Source yearly and monthly
- [x] disbursements by source yearly and monthly
- [x] disbursements by recipient yearly and monthly

Query Data @eelzi-ONRR 
- [x] trend lines 

Explore Data @eelzi-ONRR 
- [x] Commodities circle charts for revenue data
- [x]  Commodities circle charts for disbursements data
- [x]  Commodities circle charts for production data 
- [x] Horizontal chart  federal revenue by company 
- [x] Horizontal chart Nationwide revenue by revenue type and source 
- [x] Horizontal bar chart Nationwide disbursements by recipient and source
- [x] Map legend in lower left corner of map

How Revenue Works @eelzi-ONRR 
- [x] file box icon ([audits & assurances](https://revenuedata.doi.gov/how-revenue-works/audits-and-assurances))
- [x] line arrows that connect ownership, leasing, production, revenue, disbursements boxes ([How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))
- [x] ribbon graphic - major commodities in the U.S. ([How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

Throughout the website (only test 1 or 2 locations) @Maroyafaied 
- [x] ONRR logo ([About](https://revenuedata.doi.gov/about/), [fact sheet](https://revenuedata.doi.gov/fact-sheet/), [Minerals](https://revenuedata.doi.gov/how-revenue-works/minerals))
- [x] Tool tip question mark icon (many many pages. Lots can be found on [How Revenue Works](https://revenuedata.doi.gov/how-revenue-works))

### CODE REVIEW

**Review by cthomasONRR — APPROVED** [review]
All revenue, production, and OGOR-B data look good!

**Comment by eelzi-ONRR** [comment]
@Maroyafaied 
A couple things: 

- There's no alt text for the horizontal bar charts for federal revenue by company 
- The Factsheet Disbursements by Recipient chart has the old alt text. It works for this chart, but wasn't sure if you want it to be the same format as the others
- There is no revenue by recipient chart, but I did check all the revenus charts and they pass

**Review by lpgoldstein — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I updated the alt text in the fact sheet for disbursements and revenue by company bar chart should have alt text now.  You're right there's no such thing as revenue by recipient lol I mistyped that, I meant revenue by revenue type.

**Fact sheet disbursements** 
image

**Revenue by company bar chart**
image


@lpgoldstein I updated your title in the blog. 
image

**Review by eelzi-ONRR — APPROVED** [review]
Everything looks good now!

**Pull request merged**
