### PR TITLE
Data Uploads and Accessibility Statement

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/)

Changes proposed in this pull request:

- Add "known limitations" section to the [accessibility statement webpage](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/accessibility)
- Add external link indicators to the Offshore Regions pages: 
     - [Alaska](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/explore/offshore-regions/alaska/)
     - [Atlantic](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/explore/offshore-regions/atlantic/)
     - [Gulf](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/explore/offshore-regions/gulf/)
     - [Pacific](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/explore/offshore-regions/pacific/)
 - Update links on the following webpages:
     -   [Ownership: "Alaska Native Corporation"](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/how-revenue-works/ownership/)
     -    [Federal Reforms: "2019 Well Control Rule"](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/how-revenue-works/federal-reforms/)
     -    [Audits & Assurances: "Green Book"](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/how-revenue-works/audits-and-assurances/)
     -    [About: "Open Government Initiatives"](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/about/)
 - June 24 monthly revenue data
 - June 24 monthly disbursement data
 - March 24 monthly production data
 - March 24 monthly OGOR-B data

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@eelzi-ONRR I have the accessibility statement updates in this PR, if you have time to quickly review before you leave. I used this link to make sure all the intro language was consistent: https://www.w3.org/WAI/planning/statements/complete-example/. Thanks!

**Comment by eelzi-ONRR** [comment]
@cthomasONRR This great! My only suggestion is to also link the instance of "contact us" in the third bullet so the user doesn't have to jump around to find the email link. 

I'll go ahead and approve so that's not keeping you from publishing

**Review by eelzi-ONRR — APPROVED** [review]

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State 
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear all and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
Monthly revenue and production data look good!

**Comment by cthomasONRR** [comment]
@lpgoldstein If you have time, could you review the 8 links I have listed?

- Add external link indicators to the Offshore Regions pages: 
     - [Alaska](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/explore/offshore-regions/alaska/)
     - [Atlantic](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/explore/offshore-regions/atlantic/)
     - [Gulf](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/explore/offshore-regions/gulf/)
     - [Pacific](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/explore/offshore-regions/pacific/)
 - Update links on the following webpages:
     -   [Ownership: "Alaska Native Corporation"](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/how-revenue-works/ownership/)
     -    [Federal Reforms: "2019 Well Control Rule"](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/how-revenue-works/federal-reforms/)
     -    [Audits & Assurances: "Green Book"](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/how-revenue-works/audits-and-assurances/)
     -    [About: "Open Government Initiatives"](https://nrrd-preview.app.cloud.gov/sites/AccessibilityStatement/about/)

**Comment by lpgoldstein** [comment]
@cthomasONRR all links and indicators look good!

**Review by lpgoldstein — APPROVED** [review]

**Comment by lpgoldstein** [comment]
**Disbursements Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ] Breakout - Source 
- [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by lpgoldstein** [comment]
@cthomasONRR disbursements look good. I think we can release.

**Pull request merged**
