### PR TITLE
Dev-->Master Revenue True Up and Table Comparison Absolute Value Bug Fix

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] Table Comparison Bug Fix
- [x] Revenue True Up

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@Maroyafaied The preview link isn't working for me- I'm getting a 404 when I click on it.

**Comment by Maroyafaied** [comment]
@cthomasONRR I fixed it, it's the link to the dev site. Thanks

**Review by cthomasONRR — APPROVED** [review]
I see the table comparison percents updated correctly. I also downloaded the revenue excels and everything looks good to me.

**Review by Baymatt — APPROVED** [review]
@Maroyafaied Revenue looks good!

**Pull request merged**
