### PR TITLE
external-link-indicators

### LINKED ISSUE #2941: External link indicator for NRRD markdown
We want to make sure all external links in NRRD have an [external link indicator](https://fontawesome.com/v5/icons/external-link?f=classic&s=solid), but still open in the same window like they do now.

- Search web to see if there is a simple markdown command I can add to the link code.
-  If there is, I will work to implement it on all external links
-  If I cannot fix myself, I will get Jeff's help

### PR DESCRIPTION
**Pull request by cthomasONRR**
Fixes #2941

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/external-link-indicators/)

Webpages updated with external link icons:

- [ ] Download data
- [ ] Download data - Disbursements by month
- [ ] Download data - Production by month
- [ ] Download data - Production by year
- [ ] Download data - Production disposition by month
- [ ] Download data - Revenue
- [ ] Download data - Revenue by company
- [ ] Footer
- [ ] Footer - About
- [ ] Footer - Accessibility
- [ ] Footer - Information Quality
- [ ] Footer - Plain Language
- [ ] Footer - VDP
- [ ] How revenue works - AML Reclamation
- [ ] How revenue works - Audits and assurances
- [ ] How revenue works - Coal
- [ ] How revenue works - Coal excise tax
- [ ] How revenue works - Federal laws
- [ ] How revenue works - Federal reforms
- [ ] How revenue works - GOMESA
- [ ] How revenue works - HPF
- [ ] How revenue works - LWCF
- [ ] How revenue works - Minerals
- [ ] How revenue works - Native American ownership
- [ ] How revenue works - Native American production
- [ ] How revenue works - Native American revenue
- [ ] How revenue works - Oil and gas
- [ ] How revenue works - Ownership
- [ ] How revenue works - Reclamation
- [ ] How revenue works - Renewables
- [ ] How revenue works - Revenues

### CODE REVIEW

**Comment by cthomasONRR** [comment]
`<a href="google.com">the link</a>`
Does not work- no indicator but still opens in same window
image

`[link text](url){target="_blank"} `
Does not work- "{target="_blank"}" shows in text. Link still opens in same window.
image

`<a href="URL" target="_blank" >link text</a>.`
Does not work- no indicator and link now opens in new tab.
image

**Comment by cthomasONRR** [comment]
`<ExternalLink href="URL">link text</ExternalLink>`
Does not work either.
image


I think we need to install some sort of theme package?

**Comment by cthomasONRR** [comment]
This is what USWDS shows 
https://designsystem.digital.gov/components/link/ 
image

I tried this and it does not work. No external link icon for "Federal lands" and adding the new code for Federal lands somehow messed up the OCS link.
image

**Comment by cthomasONRR** [comment]
I tried the code here: https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-external-link
by just adding it to the end of the markdown format:
`[link text](link url)<i class="fa fa-external-link" style="font-size:24px"></i> a`
And it didn't do anything:
image

I think we need to install the font package (or something similar) to what's listed here https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-external-link

**Comment by cthomasONRR** [comment]
@greensomes This mui looks good! 

Is it possible to have the icon after the link text instead of before? 
image
So instead of `[<OpenInNewIcon style={{ fontSize: 20 }} /> Federal minerals](https://fas.org/sgp/crs/misc/R42346.pdf)`

Could I set it up like: `[Federal minerals <OpenInNewIcon style={{ fontSize: 20 }} />](https://fas.org/sgp/crs/misc/R42346.pdf)`

Also just want to make sure- I'll have to manually add the code to every location I want the external indicator?

**Comment by greensomes** [comment]
Hi @cthomasONRR. Yes, the position can easily be flipped. I am going through all the pages under downloads and "how revenue works" and adding the icon. There is also an import statement that needs to be added towards the top of each file to properly bring in the icon tag.

I am doing this in my local environment so that I can more quickly validate all of the changes before pushing to the preview site.

**Comment by cthomasONRR** [comment]
@greensomes Don't feel obligated to adding the code to each external link- I can go through and do that!

**Comment by greensomes** [comment]
@cthomasONRR, it's no trouble at all! I see some potential pitfalls and there are probably other things that are more important for you!

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

We finished adding the external link icon to all external and onrr.gov links. Do you have time to review? There's a lot of webpages to review, but hopefully it will be a quick check of each page. I can also tag someone else to help if this is too much. Just let me know when you're back tomorrow. Thanks!

- [ ] Download data
- [ ] Download data - Disbursements by month
- [ ] Download data - Production by month
- [ ] Download data - Production by year
- [ ] Download data - Production disposition by month
- [ ] Download data - Revenue
- [ ] Download data - Revenue by company
- [ ] Footer
- [ ] Footer - About
- [ ] Footer - Accessibility
- [ ] Footer - Information Quality
- [ ] Footer - Plain Language
- [ ] Footer - VDP
- [ ] How revenue works - AML Reclamation
- [ ] How revenue works - Audits and assurances
- [ ] How revenue works - Coal
- [ ] How revenue works - Coal excise tax
- [ ] How revenue works - Federal laws
- [ ] How revenue works - Federal reforms
- [ ] How revenue works - GOMESA
- [ ] How revenue works - HPF
- [ ] How revenue works - LWCF
- [ ] How revenue works - Minerals
- [ ] How revenue works - Native American ownership
- [ ] How revenue works - Native American production
- [ ] How revenue works - Native American revenue
- [ ] How revenue works - Oil and gas
- [ ] How revenue works - Ownership
- [ ] How revenue works - Reclamation
- [ ] How revenue works - Renewables
- [ ] How revenue works - Revenues

**Comment by eelzi-ONRR** [comment]
@cthomasONRR These all look great! I found a few other problems with links that are not related to external indicators - I'll send those to you separately

**Pull request merged**
