### PR TITLE
march-23-data

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/march-23-data/)

Changes proposed in this pull request:

- November 22 Production
- November 22 OGOR-B
- February 23 Revenue

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State (for Yearly data only)
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
@Maroyafaied February 23 Revenue isn't showing up in the preview... I definitely added the csv file to the correct folder: 
image

November 22 Production and OGORB (hyperlink text) updates are in the preview. So I'm confused why Revenue isn't showing up.

**Comment by Maroyafaied** [comment]
@cthomasONRR I saw this error in CirceCi which usually means something is off with the formatting, I formatted the revenue to be a number with two decimal places. The previous files DORC sent us had revenue formatted as a currency and this file has revenue as "general" so it didn't have two decimal places. It's building now , I'll check on it before I log off. @lpgoldstein I also uploaded monthly disbursements 
image

**Comment by lpgoldstein** [comment]
**Disbursements Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [ ] Check Treasury Fund column is deleted
- [ ] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [ ] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ] Breakout - Source 
- [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by lpgoldstein** [comment]
disbursements looks good.

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks, I'll add a bullet in the wiki about making sure revenue is formatted as "general" with 2 decimal places

**Comment by cthomasONRR** [comment]
@Maroyafaied All my data looks good!

**Pull request merged**
