### PR TITLE
dev-->master pr v7.8.1 September 17, 2024

### PR DESCRIPTION
**Pull request by lpgoldstein**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] - Added [2023 Coal Excise Tax](https://nrrd-preview.app.cloud.gov/sites/whatsnew781/how-revenue-works/coal-excise-tax/)
- [x] - Added [monthly production data](https://nrrd-preview.app.cloud.gov/sites/whatsnew781/downloads/production-by-month/)
- [x] - Added [monthly disbursements data](https://nrrd-preview.app.cloud.gov/sites/whatsnew781/downloads/disbursements-by-month/)
- [x] - Added [monthly revenue data](https://nrrd-preview.app.cloud.gov/sites/whatsnew781/downloads/revenue/)
- [x] - Added [monthly production disposition data (OGOR-B)](https://nrrd-preview.app.cloud.gov/sites/whatsnew781/downloads/production-by-disposition/)
- [x] - Updated [monthly fact sheet](https://nrrd-preview.app.cloud.gov/sites/whatsnew781/fact-sheet)

### CODE REVIEW

**Comment by lpgoldstein** [comment]
**Revenue Monthly** 	

- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State 
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear all and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Comment by lpgoldstein** [comment]
**Disbursements Monthly** 

- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source 
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Review by cthomasONRR — APPROVED** [review]
Disbursements, OGOR-B, Coal Excise Tax, and the fact sheet all look good :)

**Comment by lpgoldstein** [comment]
@cthomasONRR everything looks good to me too! I'll release first thing in the morning.

**Pull request merged**
