### PR TITLE
NRRD-Page-Updates

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/About-Page-Updates/)

Changes proposed in this pull request:

- [x] Update footer address to Denver
- [x] Added required DOI policy links to the bottom of the About page
- [x] HRW – GOMESA
- [x] HRW – Ownership
- [x] HRW – HPF
- [x] HRW – Native American production
- [x] HRW – Disbursements
- [x] HRW – Reclamation
- [x] Download data- production by year
- [x] Download data- production by month (just data dictionary)
- [x] Download data- OGOR-B (just data dictionary)
- [x] Download data - revenue
- [x] Download data - revenue by company
- [x] Download data - disbursements by month
- [x] Download data - disbursements by year
- [x] HRW - federal laws
- [x] HRW - federal reforms
- [x] HRW - coal
- [x] HRW - AML Reclamation
- [x] HRW - LWCF

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@eelzi-ONRR @lpgoldstein NRR's about page is ready for your review: https://nrrd-preview.app.cloud.gov/sites/About-Page-Updates/about. For ONRR's strategic plan, the ppt would not properly link because of the file format (having spaces in the ppt file name). I have it linked to ONRR's about page. If you think the ppt needs to be directly linked, I can try to change the file name.

**Comment by lpgoldstein** [comment]
@cthomasONRR I think it's fine to link to the page vs the pdf. Then we don't have to update the document on NRRD.

**Comment by lpgoldstein** [comment]
@cthomasONRR looks good!

**Comment by eelzi-ONRR** [comment]
@cthomasONRR Looks good!

**Comment by cthomasONRR** [comment]
Hi everyone! This is a big PR and I was hoping I could get a second set of eyes on these pages. Please check for typos. Most of these pages have very minimal rewrites, as they were all grade 12 and 11 reading levels to begin with. Thanks!

@lpgoldstein Could your review the following pages?
- [ ] Update footer address to Denver
- [ ] HRW – GOMESA
- [ ] HRW – Ownership
- [ ] HRW – HPF
- [ ] HRW – Native American production
- [ ] HRW – Disbursements
- [ ] HRW – Reclamation

@eelzi-ONRR Could you review the following pages?
- [ ] Download data- production by year
- [ ] Download data- production by month (just data dictionary)
- [ ] Download data- OGOR-B (just data dictionary)
- [ ] Download data - revenue
- [ ] Download data - revenue by company
- [ ] Download data - disbursements by month
- [ ] Download data - disbursements by year

@Maroyafaied Could you review the following pages?
- [ ] HRW - federal laws
- [ ] HRW - federal reforms
- [ ] HRW - coal
- [ ] HRW - AML Reclamation
- [ ] HRW - LWCF

**Comment by Maroyafaied** [comment]
@lpgoldstein That seemed to work for me 
image

**Comment by lpgoldstein** [comment]
https://nrrd-preview.app.cloud.gov/sites/About-Page-Updates/how-revenue-works/native-american-ownership-governance/image

**Comment by lpgoldstein** [comment]
https://nrrd-preview.app.cloud.gov/sites/About-Page-Updates/how-revenue-works/native-american-production/
image
Several agencies?

**Comment by lpgoldstein** [comment]
https://nrrd-preview.app.cloud.gov/sites/About-Page-Updates/how-revenue-works/native-american-production/
image
lower case "gas"

**Comment by Maroyafaied** [comment]
@cthomasONRR I reviewed all my pages and below are minor things I found. Thanks!

**Federal Laws**
-add "is" in the last sentence after "This fund"
image
- Remove first "and"
image

**LWCF**
- Add periods 
image

**Comment by eelzi-ONRR** [comment]
@cthomasONRR  I also found just very minor things. Mostly it looks great!

---
https://nrrd-preview.app.cloud.gov/sites/About-Page-Updates/downloads/production-by-disposition/
Disposition Description have inconsisent the spacing before the dash. Here's one of them


---

https://nrrd-preview.app.cloud.gov/sites/About-Page-Updates/downloads/revenue/
https://nrrd-preview.app.cloud.gov/sites/About-Page-Updates/downloads/federal-revenue-by-company/

Add a comma after oil value in this heading on both of these pages

**Comment by cthomasONRR** [comment]
@lpgoldstein @eelzi-ONRR @Maroyafaied Thank you all for so quickly reviewing! I have all your changes in the preview.

**Review by Maroyafaied — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@lpgoldstein @eelzi-ONRR once you approve the PR , I will merge it to dev. Thanks!

**Review by lpgoldstein — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@eelzi-ONRR I'm merging this to dev but you'll have a chance to review again in the dev to master PR.

**Comment by eelzi-ONRR** [comment]
Sorry for the delay. I know it's too late to approve, but everything looks good!

**Pull request merged**
