### PR TITLE
Dev-->Master March 2023 Release 

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] **Added blog** [about Plain Language](https://dev-blog-nrrd.app.cloud.gov/plain-language/)

- [x] **What's New** The link to the blog won't work until I publish it to the live site, it's in dev now (link above)

- [x] **Version**

**Production by disposition Monthly November 2022 and historical files**

- [x] Make sure both csv and xls files download and contain the latest data
- [x] Make sure both csv and xls files downloads open for historical data

**Production Monthly November 2022**

- [x]  Make sure the downloaded data matches the raw data. Raw data saved here

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
 

- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable

- [x]  Period - Most recent 12 months
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Source File

- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:

- [x]  One Land Type filter
- [x]  One to three Products
- [x]  Downloads matches filtered data

Download Page

- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot

- [x]  Check graphs match homepage

**Revenue Monthly February 2023**

- [x] Make sure the downloaded data matches the raw data.

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.

- [x]  Period - Fiscal Year
- [x] Period - Calendar Year
- [x]  Breakout - Source
- [x] Breakout - Revenue Type
- [x] Breakout - Commodity

 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
 

- [x]   Period - Most recent 12 months
- [x]   Period - Fiscal Year
- [x]   Period - Calendar Year
- [x]   Breakout - Source
- [x]   Breakout - Revenue Type
- [x]   Breakout Commodity

 
Homepage - Source File

- [x] -Check source file links are correct.

 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Disbursements Monthly February2023**

- [ ] Make sure RI is added to January 2017 data.
- [ ] Make sure the downloaded data matches the raw data. Raw data
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### CODE REVIEW

**Review by cthomasONRR — APPROVED** [review]
I reviewed: blog post, OGOR-B downloads, Revenue, and Production data. These sections look good. Approved!

**Review by eelzi-ONRR — APPROVED** [review]
What's new and version look good!

**Comment by Maroyafaied** [comment]
@AlexandracmONRR Can you send a screenshot of what you're seeing? This is what I'm seeing. 
image

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - I re-cached the page and it loaded correctly with the correct date! Sorry for the false alarm!

**Comment by lpgoldstein** [comment]
I checked disbursements and they look good.

**Review by AlexandracmONRR — APPROVED** [review]

**Pull request merged**
