### PR TITLE
Webpage rewrites part 2

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/webpage-rewrites-two/)

Changes proposed in this pull request:
Updates to:
- [x] /how-revenue-works/native-american-revenue/ 
- [x] /how-revenue-works/offshore-oil-gas/ 
- [x] /how-revenue-works/onshore-oil-gas/ 
- [x] /how-revenue-works/audits-and-assurances/ 
- [x] glossary
- [x] /downloads/production-by-disposition/
- [x] /about
- [x] /how-revenue-works/offshore-renewables/
- [x] /how-revenue-works/onshore-renewables/

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR I obsessed and fixed this. It was a syntax issue in the long ton definition because the parenthesis was removed before and after the quotation marks which gave an error to the categories line after it. I reverted that definition to what it used to be to get it to build, another option is to not put parenthesis or quotes. This is also updated with dev now. 
image

**Comment by Maroyafaied** [comment]
@cthomasONRR I added spaces between the paragraphs in the disposition by month download page. 
image

**Comment by cthomasONRR** [comment]
@AlexandracmONRR could you please review the following pages in the PR? Please review for typos.
- [ ] /how-revenue-works/native-american-revenue/
- [ ]  /how-revenue-works/offshore-oil-gas/
- [ ]  /how-revenue-works/onshore-oil-gas/
- [ ] /how-revenue-works/audits-and-assurances/

@Maroyafaied could you please review the following pages in the PR? Please review for typos.
- [ ] glossary
- [ ] /downloads/production-by-disposition/
- [ ] /about
- [ ] /how-revenue-works/offshore-renewables/
- [ ] /how-revenue-works/onshore-renewables/

**Review by AlexandracmONRR — APPROVED** [review]
I have submitted my comments directly to @cthomasONRR - I approve!

**Comment by Maroyafaied** [comment]
@cthomasONRR Done with my review. The only thing I found is a missing period in the glossary, not sure if it's needed.  Great job!
image

**Review by Maroyafaied — APPROVED** [review]

**Pull request merged**
