### PR TITLE
Add FY2016 monthly disbursements data 

### LINKED ISSUE #2562: Upload & Review FY 16 Disbursements monthly data

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #2562 

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/2016disbursementsdata/)

Changes proposed in this pull request:

- adds monthly FY2016 data

### CODE REVIEW

**Comment by lpgoldstein** [comment]
**Disbursements Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [ ] Check Treasury Fund column is deleted
- [ ] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [ ] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ] Breakout - Source 
- [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Disbursements Fiscal Year** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card
- With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.
    - [ ] State with data
    - [ ] State without data
    - [ ] County with data
    - [ ] County without data
    - [ ] Nationwide Federal Card
    - [ ] Native American Card

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data - In the 'Period' category, filter to 'Fiscal Year' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by lpgoldstein** [comment]
@Baymatt checklist **Disbursements Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [ ] Check Treasury Fund column is deleted
- [ ] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [ ] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ] Breakout - Source 
- [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel


**Disbursements Fiscal Year** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card
- With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.
    - [ ] State with data
    - [ ] State without data
    - [ ] County with data
    - [ ] County without data
    - [ ] Nationwide Federal Card
    - [ ] Native American Card

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data - In the 'Period' category, filter to 'Fiscal Year' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
@Baymatt if you have time, please review the CY22 production data set as well, here's the [raw file ](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Calendar%20Year%20Production/CY%20Production%20File%20as%20of%204-25-2023.csv?d=w99a99443d1cc4069a10f16e111feecd6&csf=1&web=1&e=AOfde5)

**Production Calendar Year **
	
- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Calendar%20Year%20Production/CY%20Production%20File%20as%20of%204-25-2023.csv?d=w99a99443d1cc4069a10f16e111feecd6&csf=1&web=1&e=AOfde5)

Explore Data - Map and Detail Card 
- Select a year and select a state with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected
 
- Select a year and select a county with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- Select a year and select an offshore area, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.
- [ ] Add Nationwide Federal Card and verify the expected information is displayed.
- [ ] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Production Summary and Top Nationwide Locations
- Verify breakdowns by production type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data, in the 'Period' category, filter to either 'Calendar Year' or 'Fiscal Year' and check the following:
- [ ] One Land Type filter
- [ ] One State
- [ ] One Offshore Region
- [ ] One to three Product
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
Checklist for @Maroyafaied **Production Calendar Year **
	
- [ ] Make sure the downloaded data matches the raw data. Raw data saved [here](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Production/Calendar%20Year%20Production/CY%20Production%20File%20as%20of%204-25-2023.csv?d=w99a99443d1cc4069a10f16e111feecd6&csf=1&web=1&e=AOfde5)

Explore Data - Map and Detail Card 
- Select a year and select a state with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected
 
- Select a year and select a county with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- Select a year and select an offshore area, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.
- [ ] Add Nationwide Federal Card and verify the expected information is displayed.
- [ ] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Production Summary and Top Nationwide Locations
- Verify breakdowns by production type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data, in the 'Period' category, filter to either 'Calendar Year' or 'Fiscal Year' and check the following:
- [ ] One Land Type filter
- [ ] One State
- [ ] One Offshore Region
- [ ] One to three Product
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by Maroyafaied** [comment]
@Baymatt we had a sudden request from management to release this data today. I will be merging this PR to dev soon, Lindsay and I will review in dev within the next hour then release.

**Comment by Baymatt** [comment]
@Maroyafaied Got it, I'm working through CY22 Production now, will be done soon.

**Pull request merged**
