### PR TITLE
Dev-->Master March 30 2023

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

**What's new and version** @eelzi-ONRR 
- [x] what's new section (check links are working)
- [x] version 6.8.0 (changed the middle number to 8 since we're releasing a new renewable fact sheet) 

**Links Updates**   @AlexandracmONRR 
onrr.gov hyperlinks located at:
- [x]  https://revenuedata.doi.gov/downloads
- [x]  https://revenuedata.doi.gov/how-revenue-works/federal-laws/
- [x]  https://revenuedata.doi.gov/how-revenue-works/native-american-production/
- [x]  https://revenuedata.doi.gov/how-revenue-works/native-american-revenue/

External hyperlinks located at:
- [x] https://revenuedata.doi.gov/how-revenue-works/federal-laws/
- [x] https://revenuedata.doi.gov/how-revenue-works/native-american-ownership-governance/
- [x] https://revenuedata.doi.gov/how-revenue-works/native-american-production/
- [x] https://revenuedata.doi.gov/how-revenue-works/offshore-oil-gas/
- [x] https://revenuedata.doi.gov/how-revenue-works/aml-reclamation-program
- [x] https://revenuedata.doi.gov/how-revenue-works/lwcf
- [x] https://revenuedata.doi.gov/how-revenue-works/audits-and-assurances
- [x] Footer

PDF map hyperlink
- [x] https://revenuedata.doi.gov/how-revenue-works/gomesa

**Explore Data Bug Fixes** @eelzi-ONRR 

- [x] Dropdown location menu (check all data types in explore data)
- [x] Santa Barbara county spelling (check spelling in all data types in explore data & query tool)

**Blog** @AlexandracmONRR @eelzi-ONRR 

- [x] [Modernizing a federal government website with user-centered design](https://dev-blog-nrrd.app.cloud.gov/modernize-government-website/)

**Renewable Fact Sheets**

- [x] [FY 2022 renewable fact sheet ](https://dev-nrrd.app.cloud.gov//downloads/renewables-fact-sheets/Renewables-Fact-Sheet-FY22.pdf) @lpgoldstein @AlexandracmONRR 
          - [ ] Accessible
          - [ ] Geothermal & Wind Disbursements ([ use this excel sheet to review](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Renewable%20snapshot/Geothermal%20%26%20Wind%20Disbursements.xlsx?d=w2bb9f31622f3448fa87cf11df7ec969b&csf=1&web=1&e=Uq3j9w))
          - [ ] Geothermal & Wind Revenue ([use this excel sheet to review](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Renewable%20snapshot/Geothermal%20%26%20Wind%20Revenue.xlsx?d=w154558e4dfd84f9296bf418663b482f6&csf=1&web=1&e=bGr0ve))
          - [ ] Geothermal production ([use this excel sheet to review](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Renewable%20snapshot/Geothermal%20Production%20data%20check.xlsx?d=wb765264ab65c47b7b5b709897a3e5512&csf=1&web=1&e=wS85S4))

- [x] [FY 2021 renewable fact sheet ](https://dev-nrrd.app.cloud.gov/downloads/renewables-fact-sheets/Renewables-Fact-Sheet-FY21.pdf) @cthomasONRR @AlexandracmONRR 
          - [ ] Accessible
          - [ ] Geothermal production ([use this excel sheet to review](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Renewable%20snapshot/Geothermal%20Production%20data%20check.xlsx?d=wb765264ab65c47b7b5b709897a3e5512&csf=1&web=1&e=wS85S4))
- [x] [FY 2019 renewable fact sheet](https://dev-nrrd.app.cloud.gov/downloads/renewables-fact-sheets/Renewables-Fact-Sheet-FY19.pdf) @cthomasONRR @AlexandracmONRR 
          - [ ] Accessible
          - [ ] Geothermal production ([use this excel sheet to review](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Renewable%20snapshot/Geothermal%20Production%20data%20check.xlsx?d=wb765264ab65c47b7b5b709897a3e5512&csf=1&web=1&e=wS85S4))

**FY 2023 GOMESA Disbursements** ( use press release draft forwarded to onrrweb mailbox) @eelzi-ONRR @lpgoldstein 

- [x] Alabama
- [x] Louisiana
- [x] Mississippi
- [x] Texas

**Revenue by Company CY 2022** @lpgoldstein @cthomasONRR 

Download Page
- [x] Dates and file size are correct for csv and excel
- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Click on the "Federal revenue by company" link below the map
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
  - [x]  One to three Companies
  - [x]  Revenue Types within a Company
  - [x]  One to three Commodities
  - [x]  Check the Top 10 Companies (highest revenue) to ensure revenue sums and their percent of total is correct
  - [x]  Check "Other Companies" to ensure that the revenue sum and percent of total is correct

Query Data - In the "Data Type" category, filter to "Federal revenue by company"
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
  - [x]  One to three Companies
  - [x]  One to three Revenue Types
  - [x]  One to three Commodities
  - [x]  Clear All and change grouping
  - [x]  Download matches filtered data

**Production FY 2022** @lpgoldstein @cthomasONRR 
      
- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card
- Select a year and select a state with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected
 
- Select a year and select a county with data, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- Select a year and select an offshore area, verify information on the detail cards are correct as well as the Production Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a state and county without data and verify the expected information is displayed.
- [x] Add Nationwide Federal Card and verify the expected information is displayed.
- [x] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Production Summary and Top Nationwide Locations
- Verify breakdowns by production type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [x] Not current Fiscal Year
    - [x] Current Fiscal Year

Query Data, in the 'Period' category, filter to either 'Calendar Year' or 'Fiscal Year' and check the following:
- [x] One Land Type filter
- [x] One State
- [x] One Offshore Region
- [x] One to three Product
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@lpgoldstein Dev is rebuilding now with the updated FY22 renewable fact sheet.  I forgot to add checking what's new and version to the list, @eelzi-ONRR can you check for that?

**Comment by eelzi-ONRR** [comment]
@Maroyafaied will do! Wrapping up the other parts I'm reviewing now and will get to that next

**Review by cthomasONRR — APPROVED** [review]
I checked all sections assigned to me. Everything looks good in them. Approved.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied The renewable fact sheets need a page title and language indicated to pass online accessibility. This error also happens in the downloadable PDF, so I think it can be added in acrobat and reuploaded. Otherwise the information in the FY 22 factsheet look good

**Comment by cthomasONRR** [comment]
@lpgoldstein The coal data is in "coal (ton)" I think we need developer help to remove "coal (tons)" ... this is in the live site too and not unique to this PR

**Review by lpgoldstein — APPROVED** [review]

**Comment by AlexandracmONRR** [comment]
@Maroyafaied - I'm still getting a failure of this external link - even in the NRRD Dev site: 
image

https://dev-nrrd.app.cloud.gov/how-revenue-works/lwcf/

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I just tried to get the FWS homepage to load on my personal computer and phone... not working. Looks like their site it down.

**Comment by AlexandracmONRR** [comment]
@cthomasONRR - you're right... FWS's site is VERY slow right now and is down! Okay, I will ignore any FWS links that aren't functioning correctly!

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I flagged it to check again. We can incorporate a link update for FWS at another release too.

**Comment by Maroyafaied** [comment]
@lpgoldstein @cthomasONRR should this be spelled as "pursuing" 
image

**Comment by cthomasONRR** [comment]
@Maroyafaied yep

**Comment by Maroyafaied** [comment]
If someone can please re-read and review the blog one more time, I'd appreciate it. The highlighted dark green in the pic below are the changes I just pushed (make sure you refresh). Thanks 
image

**Comment by AlexandracmONRR** [comment]
@lpgoldstein for the FY22 Renewable factsheet, should this number actually be **4,661,291,493**?

image

image

**Comment by Maroyafaied** [comment]
@AlexandracmONRR Yes, it should. Good Catch. @lpgoldstein that's the number I changed yesterday so not sure why it's back to 4. Can you please change it again to a 3 and send me the accessible pdf and I'll upload it. Thanks

**Comment by Maroyafaied** [comment]
@lpgoldstein This is the accessible pdf with the "3" before the text change. Maybe you can edit the text in the pdf since it's already accessible. 
[Renewables-Fact-Sheet-FY22.pdf](https://github.com/DOI-ONRR/nrrd/files/11105800/Renewables-Fact-Sheet-FY22.pdf)

**Review by AlexandracmONRR — APPROVED** [review]

**Comment by eelzi-ONRR** [comment]
@Maroyafaied I read through the blog again and it looks good. And your changes are in there

**Comment by lpgoldstein** [comment]
I checked out the blog again and it looks good.

**Comment by Maroyafaied** [comment]
The FY 22 renewable fact sheet is updated in dev.

**Comment by Maroyafaied** [comment]
Pushing another update to fix a misspelling in the what's new section and I also forgot to add the Fiscal year 2022 renewable fact sheet.  I will review everything again later tonight. 
image

**Pull request merged**
