### PR TITLE
Dev > Master July 2024 Release

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] What's New @AlexandracmONRR 
- [x] [Release Details](https://github.com/DOI-ONRR/nrrd/releases) @AlexandracmONRR 
- [x] State & Offshore Regions nav links on [homepage tabs](https://dev-nrrd.app.cloud.gov/) @eelzi-ONRR 
- [x] [State & Offshore Regions webpage](https://dev-nrrd.app.cloud.gov/data-by-state-offshore-region) Note: links here direct you to the live site not dev @eelzi-ONRR 
- [x] Add "known limitations" section to the [accessibility statement webpage](https://dev-nrrd.app.cloud.gov/accessibility) @eelzi-ONRR 
- [x] Add external link indicators to the Offshore Regions pages: @AlexandracmONRR 
     - [x] [Alaska](https://dev-nrrd.app.cloud.gov/explore/offshore-regions/alaska/)
     - [x] [Atlantic](https://dev-nrrd.app.cloud.gov/explore/offshore-regions/atlantic/)
     - [x] [Gulf](https://dev-nrrd.app.cloud.gov/explore/offshore-regions/gulf/)
     - [x] [Pacific](https://dev-nrrd.app.cloud.gov/explore/offshore-regions/pacific/)
 - [x] Update links on the following webpages: @lpgoldstein 
     - [x]  [Ownership: "Alaska Native Corporation](https://dev-nrrd.app.cloud.gov/how-revenue-works/ownership/)
     - [x]  [Federal Reforms: "2019 Well Control Rule"](https://dev-nrrd.app.cloud.gov/how-revenue-works/federal-reforms/)
     - [x]  [Audits & Assurances: "Green Book"](https://dev-nrrd.app.cloud.gov/how-revenue-works/audits-and-assurances)
     - [x]  [About: "Open Government Initiatives"](https://dev-nrrd.app.cloud.gov/about)
 - [x] June 24 monthly revenue data @lpgoldstein 
 - [x] June 24 monthly disbursement data @eelzi-ONRR 
 - [x] March 24 monthly production data @cthomasONRR 
 - [x] March 24 monthly OGOR-B data @cthomasONRR

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@cthomasONRR 

**OGOR-B** 
- [ ] Current Excel
- [ ] Current CSV
- [ ] Historical Excel
- [ ] Historical CSV

**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
@lpgoldstein 

**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State 
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear all and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
@eelzi-ONRR 

**Disbursements Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [ ] Breakout - Source 
- [ ] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] One to three Commodities if applicable
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Review by AlexandracmONRR — APPROVED** [review]
It looks great!

**Review by lpgoldstein — APPROVED** [review]

**Comment by lpgoldstein** [comment]
@cthomasONRR everything looks good!

**Comment by eelzi-ONRR** [comment]
Not something that needs to be fixed in this release - but was Arizona left off the state list intentionally? https://revenuedata.doi.gov/explore/states/AZ/

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Limitations typos are fixed.

@AlexandracmONRR Issue #3524 is set for you to add AZ later.

**Pull request merged**
