### PR TITLE
Dev-->Master Release 5/25/2023

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] **Added blog** [about implementing a search engine](https://dev-blog-nrrd.app.cloud.gov/search-engine/) @jessmanko please review the blog and let us know if you find any spelling or grammar errors

- [x] **Added plain language webpage** [Plain Language](https://dev-nrrd.app.cloud.gov/plain-language) @eelzi-ONRR  

- [x] **Added information information-quality** [Information Quality ](https://dev-nrrd.app.cloud.gov/information-quality) @eelzi-ONRR  

- [ ] **Updated Webpages/ Re-writes** Please review for any misspellings or grammar issues 

   - [x] https://dev-nrrd.app.cloud.gov/how-revenue-works/native-american-revenue/ @jessmanko 
   - [x] https://dev-nrrd.app.cloud.gov/how-revenue-works/offshore-oil-gas/ @eelzi-ONRR 
   - [x] https://dev-nrrd.app.cloud.gov/how-revenue-works/onshore-oil-gas/ @eelzi-ONRR 
   - [x] https://dev-nrrd.app.cloud.gov/how-revenue-works/audits-and-assurances/ @eelzi-ONRR 
   - [x] https://dev-nrrd.app.cloud.gov/glossary @Maroyafaied 
   - [x]  https://dev-nrrd.app.cloud.gov/downloads/production-by-disposition/ @lpgoldstein 
   - [x] https://dev-nrrd.app.cloud.gov /about @Maroyafaied 
   - [x] https://dev-nrrd.app.cloud.gov/how-revenue-works/offshore-renewables/ @lpgoldstein 
   - [x] https://dev-nrrd.app.cloud.gov/how-revenue-works/onshore-renewables/ @lpgoldstein 

- [x] **What's New** @Maroyafaied 

- [x] **Version**@Maroyafaied

**Production by disposition Monthly January 2023 and historical files** @Maroyafaied 

- [x] Make sure both csv and xls files download and contain the latest data
- [x] Make sure both csv and xls files downloads open for historical data

**Production Monthly January 2023** @Maroyafaied 

- [x]  Make sure the downloaded data matches the raw data. Raw data saved here

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
 

- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable

- [x]  Period - Most recent 12 months
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Source File

- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:

- [x]  One Land Type filter
- [x]  One to three Products
- [x]  Downloads matches filtered data

Download Page

- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot

- [x]  Check graphs match homepage

**Revenue Monthly April 2023** @lpgoldstein 

- [x] Make sure the downloaded data matches the raw data.

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.

- [x]  Period - Fiscal Year
- [x] Period - Calendar Year
- [x]  Breakout - Source
- [x] Breakout - Revenue Type
- [x] Breakout - Commodity

 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
 

- [x]   Period - Most recent 12 months
- [x]   Period - Fiscal Year
- [x]   Period - Calendar Year
- [x]   Breakout - Source
- [x]   Breakout - Revenue Type
- [x]   Breakout Commodity

 
Homepage - Source File

- [x] -Check source file links are correct.

 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Disbursements Monthly  April 2023** @lpgoldstein 

- [x] Make sure RI is added to January 2017 data.
- [x] Make sure the downloaded data matches the raw data. Raw data
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@Maroyafaied is this centered on purpose? https://dev-nrrd.app.cloud.gov/downloads/production-by-disposition/ 
image

**Comment by Maroyafaied** [comment]
@lpgoldstein that was always centered, this wasn't a section that was updated. We can make an issue to change the alignment for the next release.

**Comment by eelzi-ONRR** [comment]
@Maroyafaied 

[Plain Language page](https://dev-nrrd.app.cloud.gov/plain-language) - it refers to "the Department" but never specifies it's the Department of Interior. "The Department" is fist mentioned in the  first sentnce under "Our Commitment" - Can we change that to "Department of the Interior's"?
image




[Information Quality page](https://dev-nrrd.app.cloud.gov/information-quality) - in the list remove "And" from the last bullet point. The second to last bullet has an and and that's where it properly belongs. And then capitalize the I in informing
image




[Audits and Assurances](https://dev-nrrd.app.cloud.gov/how-revenue-works/audits-and-assurances/) - the first sentence says 'In the United States' twice. Suggested rewrite: In the United States, data about revenue from the extractive industries are bound by government rules and regulations.
image

**Comment by lpgoldstein** [comment]
@Maroyafaied I tried to add us as reviewers so I could approve but wasn't able to. I approve this pr!

**Comment by Maroyafaied** [comment]
@eelzi-ONRR @jessmanko Thank you for thoroughly reviewing!! I will make the updates you suggested and let you know once it's done building.

**Comment by Maroyafaied** [comment]
I'm not seeing 2012 data for OGOR B files, since @cthomasONRR uploads this dataset we might have to wait to release till she's back and also circle ci builds are failing.
image
image

**Comment by Maroyafaied** [comment]
@jessmanko @eelzi-ONRR I made the updates you suggested, please feel free to review again!

**Review by eelzi-ONRR — APPROVED** [review]
@Maroyafaied The changes look good!

**Comment by jessmanko** [comment]
@Maroyafaied Looks great!

**Pull request merged**
