### PR TITLE
dev --> master Feb 8, 2024

### PR DESCRIPTION
**Pull request by greensomes**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov)

Changes proposed in this pull request:

- [x] sitemap.xml
- [x] robots.txt
- [x] What's new box
- [x] Version
- [x] Download page content
- [x] Download files
- [x] Glossary
- [x] Process diagram
- [x] Query tool - Lindsay

### CODE REVIEW

**Comment by cthomasONRR** [comment]
This does not need to be fixed right now, but "Federal" needs to be lower case, and if possible change Indian to Native American.
image

**Comment by lpgoldstein** [comment]
Federal Sales Calendar Year

Download Page

- [ ]  Make sure the downloaded data matches the raw data. 
- [ ]  Dates and file size are correct for csv and excel

Query Data

- [ ]  One to three Commodities
- [ ]  One Land Type filter
- [ ]  One State
- [ ]  One Offshore Region
- [ ]  Add a column
- [ ]  Clear All and change grouping
- [ ]  Downloads matches filtered data

**Comment by lpgoldstein** [comment]
image
lower case oil and gas

**Comment by cthomasONRR** [comment]
Does not have to be fixed right now.... I'm not sure if "Indian" is required here, but if it isn't, we should change to Native American. 
image

**Comment by cthomasONRR** [comment]
@Maroyafaied I'm done with my review. I think it's good to go as-is. I only found minor capitalization and term fixes that do not have to be addressed asap.

**Comment by eelzi-ONRR** [comment]
Reviewed all listed pages plus the download data landing page. Didn't find anything other than what has already been put in previous comments

**Comment by AlexandracmONRR** [comment]
Other than the glossary terms that were pointed out, I think that it looks good!

**Comment by lpgoldstein** [comment]
Also done

**Pull request merged**
