### PR TITLE
Trusted-Tester-Updates

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Trusted-Tester-Updates/)

Changes proposed in this pull request:

- #2733 : Homepage fact sheet updated as a list
- #2744 : All 3 pages updated
- #2732 : All except Explore Data are updated thanks to Maroya
- #2727: Updated alt text for all logos

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR I removed the h1 heading from the query tool "Download" tab and from explore data "add a location" and "explore more" tabs.

**Comment by Maroyafaied** [comment]
@cthomasONRR @eelzi-ONRR are you both ok with merging this PR to dev?

**Comment by eelzi-ONRR** [comment]
@Maroyafaied  I just did another final review and yes - looks good to merge

**Comment by cthomasONRR** [comment]
@Maroyafaied Yes, thanks!

**Pull request merged**
