### PR TITLE
Dev-->Master November 27,2023

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

- [x] What's New & Version @lpgoldstein 

- [x] [Agile management blog ](https://dev-blog-nrrd.app.cloud.gov/federal-team/) @AlexandracmONRR 

- [x] External links indicators @cthomasONRR 

- [x] Revenue by company download column name changes @greensomes 

- [x] Colored squares alt text @eelzi-ONRR 

**Production by disposition Monthly July 2023 and historical files** @cthomasONRR

- [x] Make sure both csv and xls files download and contain the latest data
- [x] Make sure both csv and xls files downloads open for historical data

**Production Monthly July 2023** @cthomasONRR

- [x]  Make sure the downloaded data matches the raw data. Raw data saved here

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
- [x]  Period - Most recent 12 months
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x]  One Land Type filter
- [x]  One to three Products
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x]  Check graphs match homepage

**Revenue Monthly October  2023** @cthomasONRR 
- [x] Make sure the downloaded data matches the raw data.

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x]  Period - Fiscal Year
- [x] Period - Calendar Year
- [x]  Breakout - Source
- [x] Breakout - Revenue Type
- [x] Breakout - Commodity

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
- [x]   Period - Most recent 12 months
- [x]   Period - Fiscal Year
- [x]   Period - Calendar Year
- [x]   Breakout - Source
- [x]   Breakout - Revenue Type
- [x]   Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State (for Yearly data only)
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Disbursements Monthly October 2023** @lpgoldstein

- [x] Make sure the downloaded data matches the raw data. Raw data
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

### CODE REVIEW

**Comment by cthomasONRR** [comment]
@Maroyafaied Should the monthly fact sheet be linked in What's New?
image

**Comment by cthomasONRR** [comment]
External link checklist:

- [ ] Download data
- [ ] Download data - Disbursements by month
- [ ] Download data - Production by month
- [ ] Download data - Production by year
- [ ] Download data - Production disposition by month
- [ ] Download data - Revenue
- [ ] Download data - Revenue by company
- [ ] Footer
- [ ] Footer - About
- [ ] Footer - Accessibility
- [ ] Footer - Information Quality
- [ ] Footer - Plain Language
- [ ] Footer - VDP
- [ ] How revenue works - AML Reclamation
- [ ] How revenue works - Audits and assurances
- [ ] How revenue works - Coal
- [ ] How revenue works - Coal excise tax
- [ ] How revenue works - Federal laws
- [ ] How revenue works - Federal reforms
- [ ] How revenue works - GOMESA
- [ ] How revenue works - HPF
- [ ] How revenue works - LWCF
- [ ] How revenue works - Minerals
- [ ] How revenue works - Native American ownership
- [ ] How revenue works - Native American production
- [ ] How revenue works - Native American revenue
- [ ] How revenue works - Oil and gas
- [ ] How revenue works - Ownership
- [ ] How revenue works - Reclamation
- [ ] How revenue works - Renewables
- [ ] How revenue works - Revenues

**Comment by eelzi-ONRR** [comment]
@cthomasONRR @Maroyafaied The fact sheet is updated for me: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGI5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--939284acb9ad874682d9f88bd4118dcb2a8b0637/image.png)

**Comment by cthomasONRR** [comment]
@eelzi-ONRR Thanks- I clicked the link within the fact sheets tab and didn't notice that it sends me to the live site. The fact sheets link in the footer brought me to the correct location in dev. I see the updated fact sheet in dev, but still think it needs to be linked in What's New.

**Comment by Maroyafaied** [comment]
@cthomasONRR thanks for catching that, I added the fact sheet link to the what's new. Thanks 
image

**Review by cthomasONRR — APPROVED** [review]
@Maroyafaied I reviewed everything assigned to me. Thanks for adding the fact sheet to What's New. Everything I checked looks good. Approve :)

**Review by lpgoldstein — APPROVED** [review]

**Review by AlexandracmONRR — APPROVED** [review]

**Review by eelzi-ONRR — APPROVED** [review]

**Review by greensomes — APPROVED** [review]

**Pull request merged**
