### PR TITLE
Feb-24-Uploads

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Feb-24-Uploads/)

Changes proposed in this pull request:

- October 23 Production
- October 23 OGOR-B
- January 24 Revenue

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State 
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
@greensomes I'm seeing differences in January 24 monthly revenue for Federal Onshore. I'm investigating why this is happening. If I figure it out, I'll post it here.
PR:
image
Raw Data:
image

**Comment by cthomasONRR** [comment]
@greensomes I'm seeing the same errors in the downloadable Excel. It looks like for Jan 24 - Federal -Onshore - Royalties & Other Revenues - These commodities are NOT included: Oil, Gas, NGLs. I'm not sure how, but instances of Oil, Gas, NGL, and maybe some O&G pre-production did not translate from the raw file to the PR.

**Comment by cthomasONRR** [comment]
Also, I'm checking the raw data from previous months. Previous months data match, so this is just confined to January 24 not the entire dataset.

**Comment by cthomasONRR** [comment]
I see this in CircleCi, I'm not sure if this could be the culprit. Very small rounding differences less than a dollar are common in monthly revenue. But having a difference of $164,968.92 between PR and raw is not the norm. I can't directly ID any errors in the raw data. I'm sorry I'm not more help! 
image

**Comment by greensomes** [comment]
Hey there! It looks like the deltas are caused by some bad data in our location table. The updated data contains data for the ND county of Golden Valley. However, the record in our location table has the county as "Golden Valle". I will include a Liquibase update to fix this. Thanks!

**Comment by greensomes** [comment]
After applying the location fix and rerunning the load, the onshore numbers now match the raw data. 👌

**Comment by lpgoldstein** [comment]
**Disbursements Monthly December 2023** @lpgoldstein

- [x] Make sure the downloaded data matches the raw data. Raw data
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Comment by lpgoldstein** [comment]
@greensomes data looks good. ready to merge.

**Pull request merged**
