### PR TITLE
revenue-true-up

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/revenue-true-up-23/)

Changes proposed in this pull request:

- Updated revenue data from January 2012 - October 2022

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR this is working now.

**Comment by Maroyafaied** [comment]
The data is not looking right though so I'll have to look into why. 
image

**Comment by Maroyafaied** [comment]
@cthomasONRR I fixed the issue above, the revenue was formatted as currency and it needs to be formatted as number. 
image

**Comment by cthomasONRR** [comment]
@Maroyafaied Thanks!!! I will add this format issue to the wiki!

**Comment by cthomasONRR** [comment]
@Baymatt This is ready for your review. The true-up file can be found [here](https://doimspp.sharepoint.com/:x:/r/sites/NRRD/Shared%20Documents/General/NRRD/Data/Revenue/FY%202023/NRRD%20Revenue%20True-up.xlsx?d=w9e6d94b36a2341a9a55435e4aa9a37b1&csf=1&web=1&e=FLGNY2).

I'm currently reviewing, and everything looks good so far!

**Comment by cthomasONRR** [comment]
I'm checking the changes Andrew listed in his email. So far, everything is matching up except I'm seeing a total variance of -$20,918.50 instead of his listed -$20,913.62. I feel like this is close enough that it's not worth bringing up.

The download files look good, and I'm using them to cross-check Andrew's email.

image

**Comment by Maroyafaied** [comment]
@Baymatt have you had a chance to review this PR yet?

**Comment by Maroyafaied** [comment]
@Baymatt I'm merging this to dev so you can review it in the dev to master PR today if you have the time.

**Pull request merged**
