### PR TITLE
Create effective-revenue-rate.mdx

### LINKED ISSUE #2886: Develop ERR download page in a PR

### PR DESCRIPTION
**Pull request by lpgoldstein**
Fixes #2886

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/err-download-page/downloads/federal-sales/)

Changes proposed in this pull request:
- creates a new err download page

### CODE REVIEW

**Comment by lpgoldstein** [comment]
@greensomes Can you please re-run for me when you have a chance? No hurry, just made a few edits.

**Comment by lpgoldstein** [comment]
@greensomes can you please rerun this build for me when you have a chance?

**Comment by Maroyafaied** [comment]
@lpgoldstein please let @greensomes know when you are done making changes to the download page since he is merging everything to one branch.

**Comment by Maroyafaied** [comment]
@greensomes @lpgoldstein I'm closing this PR to avoid confusion since we agreed we can use the 'federal-sales-data' branch to make content updates.

**Pull request closed without merging**
