### PR TITLE
Dev-->Master April 17, 2024

### PR DESCRIPTION
**Pull request by eelzi-ONRR**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] **What's New** @AlexandracmONRR 
- [x] **Version update** @AlexandracmONRR 
-  Check version is 7.4.0

**Webpage updates** @eelzi-ONRR, @AlexandracmONRR 
- [x]  https://dev-nrrd.app.cloud.gov/downloads/federal-sales/ @eelzi-ONRR 
- [x] https://dev-nrrd.app.cloud.gov/404/ @AlexandracmONRR 

**Renewables Factsheets** @AlexandracmONRR 
Check links on homepage and that data on sheets is correct
- [x] 2023
- [x] 2022
- [x] 2021

  

**Production by disposition (OGOR-B) Monthly December 2023 and historical files** @cthomasONRR

- [x]  Make sure both csv and xls files download and contain the latest data
- [x] Make sure both csv and xls files downloads open for historical data

**Production Monthly December 2023** @cthomasONRR
- [x]  Make sure the downloaded data matches the raw data. Raw data saved here

Homepage - Yearly Breakdown

- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Monthly Breakdown

- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable

- [x]  Period - Most recent 12 months
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Commodity - Oil (bbl)
- [x]  Commodity - Gas (mcf)
- [x]  Commodity - Coal (tons)

Homepage - Source File
- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Land Type filter
- [x]  One to three Products
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Revenue Monthly March 2024** @cthomasONRR
- [x] Make sure the downloaded data matches the raw data.

Homepage - Yearly Breakdown

- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Breakout - Source
- [x]  Breakout - Revenue Type
- [x]  Breakout - Commodity

Homepage - Monthly Breakdown

- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable

- [x]  Period - Most recent 12 months
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Breakout - Source
- [x]  Breakout - Revenue Type
- [x]  Breakout Commodity

Homepage - Source File

- [x] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:

- [x]  One Land Type filter
- [x]  One Revenue Type filter
- [x]  One State (for Yearly data only)
- [x]  One Offshore Region
- [x]  One to three Commodities
- [x]  Clear All and change grouping
- [x]  Downloads matches filtered data

Download Page

 

- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot

- [x] Check graphs match homepage

**Disbursements Monthly March 2024** @lpgoldstein

- [ ] Make sure the downloaded data matches the raw data. Raw data
- Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [ ]  Check Treasury Fund column is deleted
- [ ]  Check Hidalgo Caounty is changed to Hidalgo County under county column
- [ ]  Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown

- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.

- [x]  Breakout - Source
- [x]  Breakout - Recipient

Homepage - Monthly Breakdown

- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
- [x]  Period - Most recent 12 months
- [x]  Period - Fiscal Year
- [x]  Period - Calendar Year
- [x]  Breakout - Source
- [x]  Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:

- [x]  One Recipient
- [x]  One Source
- [x]  One State
- [x]  One to three Commodities if applicable
- [x]  Clear All and change grouping
- [x]  Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Revenue by Company CY 2023** @lpgoldstein @cthomasONRR

Download Page

- [x]  Dates and file size are correct for csv and excel
- [x]  Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Click on the "Federal revenue by company" link below the map

- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
- [x] One to three Companies
- [x]  Revenue Types within a Company
- [x]  One to three Commodities
- [x]  Check the Top 10 Companies (highest revenue) to ensure revenue sums and their percent of total is correct
- [x]  Check "Other Companies" to ensure that the revenue sum and percent of total is correct

Query Data - In the "Data Type" category, filter to "Federal revenue by company"

- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
- [x] One to three Companies
- [x]  One to three Revenue Types
- [x]  One to three Commodities
- [x]  Clear All and change grouping
- [x]  Download matches filtered data

**Federal Sales Calendar Year 2023 @lpgoldstein** 

Download Page
- [x] Make sure the downloaded data matches the raw data.
- [x]  Dates and file size are correct for csv and excel

Query Data
- [x] One to three Commodities
- [x]  One Land Type filter
- [x]  One State
- [x]  One Offshore Region
- [x]  Add a column
- [x]  Clear All and change grouping
- [x]  Downloads matches filtered data

### CODE REVIEW

**Comment by AlexandracmONRR** [comment]
What's new box review: 

- Add the regular monthly fact sheet needs to be added to What's new box.
- Update the last bullet to "monthly production disposition data (OGOR-B)" _I think this will be useful for people who may think of it under 2 names_

**Comment by AlexandracmONRR** [comment]
Factsheets:
- Fix rounding error on FY23 factsheet for sum of disbursement to $620,273,477
image

**Comment by cthomasONRR** [comment]
@AlexandracmONRR I think the disbursement total is intentional so that it matches the geothermal and wind rounded numbers summed. @lpgoldstein Please correct me if I'm wrong.

**Review by greensomes — APPROVED** [review]

**Comment by lpgoldstein** [comment]
@cthomasONRR you are correct @AlexandracmONRR it's a rounded number.

**Comment by AlexandracmONRR** [comment]
@lpgoldstein and @cthomasONRR - thank you for clarifying!

**Review by cthomasONRR — APPROVED** [review]

**Comment by AlexandracmONRR** [comment]
Factsheet FY21:
- Fix the descriptive text numbers to match the bubble chart of 78% and 22%.
image

**Comment by cthomasONRR** [comment]
@AlexandracmONRR The 58% and 42% refer to the state and treasury recipients, not geothermal and wind
image

**Review by AlexandracmONRR — APPROVED** [review]

**Pull request merged**
