### PR TITLE
Dev-->Master

### PR DESCRIPTION
**Pull request by Maroyafaied**
[:sunglasses: PREVIEW](https://dev-nrrd.app.cloud.gov/)

Changes proposed in this pull request:

- [x] What's new @Maroyafaied 
- [x] Version @Maroyafaied 

**September 2023 Disbursements @lpgoldstein** 
- [x] Make sure the downloaded data matches the raw data. Raw data
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**FY 15 Monthly Disbursements and FY 2023 @lpgoldstein** 
- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card
- With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.
    - [x] State with data
    - [x] State without data
    - [x] County with data
    - [x] County without data
    - [x] Nationwide Federal Card
    - [x] Native American Card

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.
    - [x] Not current Fiscal Year
    - [x] Current Fiscal Year

Query Data - In the 'Period' category, filter to 'Fiscal Year' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

**September 2023 Monthly Revenue @cthomasONRR** 
- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Revenue Type
    - [x] Breakout Commodity
 
Homepage - Source File
- [x] Check source file links are correct.
 
Explore Data - Map and Detail Card
- Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected
 
- Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Calendar Year
    - [x] Period - Fiscal Year
    - [x] With only 2-3 commodities selected.
 
- [x] Select a state and county without data and verify the expected information is displayed.
- [x] Add Nationwide Federal Card and verify the expected information is displayed.
- [x] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Calendar Year
    - [ ] Current Calendar Year
    - [x] Not current Fiscal Year
    - [x] Current Fiscal Year

Query Data
- With a selected fiscal or calendar year range, verify the data is correct and then for the conditions below. 
   - [x] One Land Type filter
   - [x] One Revenue Type filter
   - [x] One State 
   - [x] One Offshore Region
   - [x] One to three Commodities
   - [x] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

**Coal Excise Tax**
- [x] 2022 Coal Excise Tax @cthomasONRR

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@lpgoldstein @greensomes we need to update this to be 2023, is it ok if I do it straight in dev or will that mess with anything 
image

**Comment by cthomasONRR** [comment]
@greensomes The September Revenue data looks good. The only issue I'm seeing is October monthly revenue present in the data downloads. It's not in any of the visualizations.
image

**Review by cthomasONRR — APPROVED** [review]
Approving this PR- Jeff verified that the October data in the excels won't go live.

**Comment by Maroyafaied** [comment]
@lpgoldstein I updated the year to 2023 in the disbursement yearly download page and added FY15 disbursements to the what's new section. I just saw that the monthly disbursement download page needs to be updated too so I'll do that now. 
image

**Review by lpgoldstein — APPROVED** [review]

**Comment by lpgoldstein** [comment]
@Maroyafaied I see your changes and approve.

**Review by greensomes — APPROVED** [review]

**Pull request merged**
