### PR TITLE
April-24-Data-Uploads

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/April-24-Data-Uploads/)

Changes proposed in this pull request:

- CY23 Federal Revenue by Company, following instructions [here](https://github.com/DOI-ONRR/nrrd/wiki/Releasing-changes-to-production#revenue---federal-revenue-by-company).
- FY21 Fact Sheet update (Total revenue location number, check when in Dev)
- FY22 Fact Sheet update (Production numbers, check when in Dev)
- FY23 Fact Sheet (check when in Dev)
- Dec 23 monthly production
- Dec 23 monthly OGOR-B
- March 24 monthly revenue
- March 24 monthly disbursements
- CY23 federal sales data

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Revenue by Company**

Download Page
- [ ] Dates and file size are correct for csv and excel
- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Click on the "Federal revenue by company" link below the map
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
  - [ ]  One to three Companies
  - [ ]  Revenue Types within a Company
  - [ ]  One to three Commodities
  - [ ]  Check the Top 10 Companies (highest revenue) to ensure revenue sums and their percent of total is correct
  - [ ]  Check "Other Companies" to ensure that the revenue sum and percent of total is correct

Query Data - In the "Data Type" category, filter to "Federal revenue by company"
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year
  - [ ]  One to three Companies
  - [ ]  One to three Revenue Types
  - [ ]  One to three Commodities
  - [ ]  Clear All and change grouping
  - [ ]  Download matches filtered data

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Revenue Monthly** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State 
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
@greensomes We can discuss next week, but the March 24 fed onshore number in the PR is not matching the raw data:
image
image

**Comment by cthomasONRR** [comment]
@greensomes Also for discussion next week- I can't get the new Federal Revenue by Company to display in the PR. I'll set up a meeting on Tuesday for us to discuss these issues.

At least monthly production looks good!

**Comment by lpgoldstein** [comment]
Download Page
- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
- [ ] Dates and file size are correct for csv and excel

Query Data
   - [ ] One to three Commodities
   - [ ] One Land Type filter
   - [ ] One State 
   - [ ] One Offshore Region
   - [ ] Add a column
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

**Comment by lpgoldstein** [comment]
- [x] Make sure the downloaded data matches the raw data. Raw data
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.
- [x] Check Treasury Fund column is deleted
- [x] Check Hidalgo Caounty is changed to Hidalgo County under county column
- [x] Check "BLM - Permit Processing and Improvement" is changed to to "Lease Processing and Improvement" (BLM) under fund type column

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Comment by lpgoldstein** [comment]
@cthomasONRR This is ready to merge if that's okay with you?

**Comment by cthomasONRR** [comment]
@lpgoldstein Awesome! Yes, let's merge

**Pull request merged**
