### PR TITLE
NRRD webpage rewrites

### PR DESCRIPTION
**Pull request by cthomasONRR**
Rewrite issues #2488 , #2489 , #2502

[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/)

Changes proposed in this pull request:

- [x] https://revenuedata.doi.gov/how-revenue-works
- [x] https://revenuedata.doi.gov/how-revenue-works/native-american-ownership-governance/
- [x] https://revenuedata.doi.gov/how-revenue-works/minerals
- [x] https://revenuedata.doi.gov/downloads
- [x] https://revenuedata.doi.gov/how-revenue-works/revenues
- [x] https://revenuedata.doi.gov/how-revenue-works/native-american-revenue/
- [x] https://revenuedata.doi.gov/how-revenue-works/offshore-oil-gas/
- [x] https://revenuedata.doi.gov/how-revenue-works/onshore-oil-gas/
- [x] https://revenuedata.doi.gov/how-revenue-works/audits-and-assurances

### CODE REVIEW

**Comment by Maroyafaied** [comment]
@cthomasONRR I was able to get it to build.  It needed a line break at the end of the paragraph with the link since you're adding a line break to the one above it. 

image
image

**Comment by cthomasONRR** [comment]
I need a second set of eyes to help review these pages for any typos that I might have missed.

@AlexandracmONRR Could you review these webpages for typos?
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works/native-american-ownership-governance/
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works/minerals
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/downloads

@lpgoldstein Could you review the webpages for typos?
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works/revenues
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works/native-american-revenue/
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works/offshore-oil-gas
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works/onshore-oil-gas/
- [ ] https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works/audits-and-assurances

Thanks!

**Comment by lpgoldstein** [comment]
@cthomasONRR under https://nrrd-preview.app.cloud.gov/sites/Webpage-Rewrites/how-revenue-works/revenues

I'm not sure if you want the "m" in the last one or not. I think implied is fine. 

image

**Comment by cthomasONRR** [comment]
@lpgoldstein I can add it.

**Comment by AlexandracmONRR** [comment]
Native American Ownership Governance:

The highlighted bullets seem vague - is there a more specific title for the regulations? Or, the linked text may be the title, and in that case, please disregard this comment.
image

I think the highlighted "T" can be lowercase:
image


I think this would read better as "DOI" or "Department of Interior":
image

**Comment by cthomasONRR** [comment]
@AlexandracmONRR Those are the regulation citations, they are used regularly. Title is supposed to be capitalized here, as we are referring to specific Titles. You'll see the same thing for the word "Act". I can change "Interior" to DOI.

**Review by AlexandracmONRR — APPROVED** [review]

**Comment by Maroyafaied** [comment]
@cthomasONRR Is this PR ready to be merged to Dev?

**Comment by cthomasONRR** [comment]
@Maroyafaied I think so- all pages have been reviewed!

**Comment by Maroyafaied** [comment]
@cthomasONRR Thanks. I just reviewed quickly  the how revenue works main page, can you make these changes before we merge to dev. Thanks

- Fix spelling to "Learn"
image

- Replace "by production phase" with "by revenue type"
image

- Fix spelling to "receive"
image

- Fix spelling to "entities"
image

**Comment by cthomasONRR** [comment]
@Maroyafaied Just pushed those fixes out. Maybe we should wait so I can reread all the pages again.

**Comment by cthomasONRR** [comment]
@Maroyafaied I reviewed all the pages again. I think this is ready to merge now, but feel free to spot-check. Thanks!

**Pull request merged**
