### PR TITLE
monthly-upload

### PR DESCRIPTION
**Pull request by cthomasONRR**
[:sunglasses: PREVIEW](https://nrrd-preview.app.cloud.gov/sites/monthly-upload/)

Changes proposed in this pull request:

- monthly OGOR-B
- monthly production
- monthly revenue

### CODE REVIEW

**Comment by cthomasONRR** [comment]
**Production Monthly** 

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Commodity - Oil (bbl)
    - [ ] Commodity - Gas (mcf)
    - [ ] Commodity - Coal (tons)

Homepage - Source File
- [ ] Check source file links are correct.

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [ ] One Land Type filter
- [ ] One to three Products
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [ ] Check graphs match homepage

**Comment by cthomasONRR** [comment]
**Revenue Fiscal Year** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout - Commodity
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [ ] Period - Most recent 12 months
    - [ ] Period - Fiscal Year
    - [ ] Period - Calendar Year
    - [ ] Breakout - Source
    - [ ] Breakout - Revenue Type
    - [ ] Breakout Commodity
 
Homepage - Source File
- [ ] Check source file links are correct.
 
Explore Data - Map and Detail Card
- Select a year and select a state with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected
 
- Select a year and select a county with data, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- Select a year and select an offshore area, verify information on the detail cards are correct as well as the Revenue Over Time line graph. Repeat with the latest available year.
    - [ ] Period - Fiscal Year
    - [ ] With only 2-3 commodities selected.
 
- [ ] Select a state and county without data and verify the expected information is displayed.
- [ ] Add Nationwide Federal Card and verify the expected information is displayed.
- [ ] Add Native American Card and verify the expected information is displayed.

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by revenue type and source are correct as well nationwide locations for the conditions below.
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data
- With a selected fiscal or calendar year range, verify the data is correct and then for the conditions below. 
   - [ ] One Land Type filter
   - [ ] One Revenue Type filter
   - [ ] One State 
   - [ ] One Offshore Region
   - [ ] One to three Commodities
   - [ ] Clear All and change grouping
   - [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by cthomasONRR** [comment]
Production data looks good!

**Comment by greensomes** [comment]
The FY revenue data did not load properly due to a duplicate October 2024 record in the `period` table. I removed the record, manually triggered the circleci build, and refreshed the materialized views in dev and everything looks good.

**Comment by cthomasONRR** [comment]
All revenue data looks good! Yay!

**Comment by lpgoldstein** [comment]
**Disbursements Monthly** 

- [x] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)
     * Note: Make sure both datasets have the same sum. If there are line items that have the same fund type, revenue type, and location, they will be 'rolled up' together so the line item count may differ between the raw data and downloaded data.

Homepage - Yearly Breakdown
- Select a year and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent year.
- [x] Breakout - Source 
- [x] Breakout - Recipient
 
Homepage - Monthly Breakdown
- Select a month and verify the amounts and comparisons are correct for the conditions below. Repeat with the most recent month. Be sure to verify negative numbers are correct if applicable
    - [x] Period - Most recent 12 months
    - [x] Period - Fiscal Year
    - [x] Period - Calendar Year
    - [x] Breakout - Source
    - [x] Breakout - Recipient

Query Data - In the 'Period' category, filter to 'Monthly' and check the following:
- [x] One Recipient
- [x] One Source
- [x] One State
- [x] One to three Commodities if applicable
- [x] Clear All and change grouping
- [x] Downloads matches filtered data

Download Page
- [x] Dates and file size are correct for csv and excel

Monthly Snap Shot
- [x] Check graphs match homepage

**Comment by lpgoldstein** [comment]
**Disbursements Fiscal Year** 	

- [ ] Make sure the downloaded data matches the raw data. Raw data saved here (Insert Teams link to raw file)

Explore Data - Map and Detail Card
- With a fiscal year selected, verify the detail card and Disbursements Over Time are correct for the conditions below. Repeat with the current fiscal year.
    - [ ] State with data
    - [ ] State without data
    - [ ] County with data
    - [ ] County without data
    - [ ] Nationwide Federal Card
    - [ ] Native American Card

Explore Data - Nationwide Revenue Summary and Top Nationwide Locations
- Verify breakdowns by disbursement recipient and source are correct as well nationwide recipients for the conditions below.
    - [ ] Not current Fiscal Year
    - [ ] Current Fiscal Year

Query Data - In the 'Period' category, filter to 'Fiscal Year' and check the following:
- [ ] One Recipient
- [ ] One Source
- [ ] One State
- [ ] Clear All and change grouping
- [ ] Downloads matches filtered data

Download Page
- [ ] Dates and file size are correct for csv and excel

**Comment by lpgoldstein** [comment]
Disbursements looks good!

**Review by lpgoldstein — APPROVED** [review]

**Pull request merged**
